CREATE TABLE NOTIFICATIONS
(
    ID              VARCHAR(255) NOT NULL PRIMARY KEY,
    DEVICE_ID       VARCHAR(255),
    MEDIA_ITEM_ID   VARCHAR(255),
    METADATA_TAG_ID VARCHAR(255),
    TYPE            VARCHAR(255),
    NAME            VARCHAR(255) NOT NULL,
    VALUE           CLOB,
    CONTEXT         TEXT
);

CREATE INDEX IDX_NOTIFICATIONS_DEVICE_ID ON NOTIFICATIONS (DEVICE_ID);
CREATE INDEX IDX_NOTIFICATIONS_MEDIA_ITEM_ID ON NOTIFICATIONS (MEDIA_ITEM_ID);
CREATE INDEX IDX_NOTIFICATIONS_METADATA_TAG_ID ON NOTIFICATIONS (METADATA_TAG_ID);
CREATE INDEX IDX_NOTIFICATIONS_TYPE ON NOTIFICATIONS (TYPE);
CREATE INDEX IDX_NOTIFICATIONS_NAME ON NOTIFICATIONS (NAME);
