CREATE TABLE METADATA
(
    ID            VARCHAR(255) NOT NULL PRIMARY KEY,
    MEDIA_ITEM_ID UUID,
    DIRECTORY     VARCHAR(255) NOT NULL,
    NAME          VARCHAR(255) NOT NULL,
    TAG_TYPE      INTEGER      NOT NULL,
    VALUE_TYPE    VARCHAR(255) NOT NULL,
    RAW           CLOB,
    DESCRIPTION   CLOB
);

CREATE INDEX IDX_METADATA_MEDIA_ITEM_ID ON METADATA (MEDIA_ITEM_ID);
CREATE INDEX IDX_METADATA_DIRECTORY ON METADATA (DIRECTORY);
CREATE INDEX IDX_METADATA_NAME ON METADATA (NAME);
CREATE INDEX IDX_METADATA_TAG_TYPE ON METADATA (TAG_TYPE);
CREATE INDEX IDX_METADATA_VALUE_TYPE ON METADATA (VALUE_TYPE);

