CREATE TABLE MEDIA
(
    ID                VARCHAR(255) NOT NULL PRIMARY KEY,
    DEVICE_ID         UUID,
    NAME              VARCHAR(255) NOT NULL,
    URI               TEXT         NOT NULL,
    LENGTH            BIGINT       NOT NULL,
    HASH              VARCHAR(255),
    CONTENT_HASH      VARCHAR(255),
    IMAGEFORMAT       VARCHAR(255),
    VIDEOFORMAT       VARCHAR(255),
    VIDEOCODINGFORMAT VARCHAR(255),
    AUDIOCODINGFORMAT VARCHAR(255),
    LOCKED            BOOLEAN      NOT NULL,
    CREATED_AT        TIMESTAMP    NOT NULL,
    UPDATED_AT        TIMESTAMP    NOT NULL,
    DELETED_AT        TIMESTAMP
);

CREATE INDEX IDX_MEDIA_DEVICE_ID ON MEDIA (DEVICE_ID);
CREATE INDEX IDX_MEDIA_NAME ON MEDIA (NAME);
CREATE INDEX IDX_MEDIA_LENGTH ON MEDIA (LENGTH);
CREATE INDEX IDX_MEDIA_HASH ON MEDIA (HASH);
CREATE INDEX IDX_MEDIA_CONTENT_HASH ON MEDIA (CONTENT_HASH);
CREATE INDEX IDX_MEDIA_LOCKED ON MEDIA (LOCKED);
CREATE INDEX IDX_MEDIA_CREATED_AT ON MEDIA (CREATED_AT);
CREATE INDEX IDX_MEDIA_UPDATED_AT ON MEDIA (UPDATED_AT);
CREATE INDEX IDX_MEDIA_DELETED_AT ON MEDIA (DELETED_AT);

